### ISSUE TITLE
Controller vibration still invalid

### ISSUE THREAD

**Issue by h469211620** [MikeCoder96/chiaki-custom#2]
ds4 ，switch pro ，xbox one controller still cannot vibrate after being connected.After the controller is connected, it still does not vibrate.When will it support controller vibration like moonlight?

**Comment by MikeCoder96** [comment]
I was able to try it via ds5 controller. I will try with xbox controller after vacation

**Comment by MikeCoder96** [comment]
Vibration work properly only if you connect the controller via cable.
Anyway, I will drop support for this project so I suggest to support [PSPlay](https://www.reddit.com/r/PSPlay/), the developer is working hard on it.
